const BASE_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:5000/api';

// Helper to handle response
const handleResponse = async (response) => {
    if (!response.ok) {
        const error = await response.json().catch(() => ({ message: 'Something went wrong' }));
        throw new Error(error.message || 'API Error');
    }
    return response.json();
};

// --- Teachers ---
export const fetchTeachers = async () => {
    const res = await fetch(`${BASE_URL}/teachers`);
    return handleResponse(res);
};

export const createTeacher = async (data) => {
    const res = await fetch(`${BASE_URL}/teachers`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(data),
    });
    return handleResponse(res);
};

export const updateTeacher = async (id, data) => {
    const res = await fetch(`${BASE_URL}/teachers/${id}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(data),
    });
    return handleResponse(res);
};

export const deleteTeacher = async (id) => {
    const res = await fetch(`${BASE_URL}/teachers/${id}`, {
        method: 'DELETE',
    });
    return handleResponse(res);
};

// --- Departments ---
export const fetchDepartments = async () => {
    const res = await fetch(`${BASE_URL}/departments`);
    return handleResponse(res);
};

export const createDepartment = async (data) => {
    const res = await fetch(`${BASE_URL}/departments`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(data),
    });
    return handleResponse(res);
};

export const deleteDepartment = async (id) => {
    const res = await fetch(`${BASE_URL}/departments/${id}`, {
        method: 'DELETE',
    });
    return handleResponse(res);
};

// --- Subjects ---
export const fetchSubjects = async () => {
    const res = await fetch(`${BASE_URL}/subjects`);
    return handleResponse(res);
};

// --- Rooms ---
export const fetchRooms = async () => {
    const res = await fetch(`${BASE_URL}/rooms`);
    return handleResponse(res);
};

// --- Routines ---
export const fetchRoutines = async () => {
    const res = await fetch(`${BASE_URL}/routines`);
    return handleResponse(res);
};

export const fetchRoutineById = async (id) => {
    const res = await fetch(`${BASE_URL}/routines/${id}`);
    return handleResponse(res);
};
export const createRoutine = async (data) => {
    // Check if ID is needed or generated by backend. 
    // Frontend was generating ID: `${routine.department}-${routine.semester}-${routine.shift}-${routine.group}`
    // Backend typically stores in MongoDB with _id.
    // But for compatibility with frontend logic which presumably uses this ID for lookups, 
    // we might need to send it or let backend generate.
    // For now, I'll send the data as is.
    const res = await fetch(`${BASE_URL}/routines`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(data),
    });
    return handleResponse(res);
};

export const updateRoutine = async (id, data) => {
    const res = await fetch(`${BASE_URL}/routines/${id}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(data),
    });
    return handleResponse(res);
};

export const deleteRoutine = async (id) => {
    const res = await fetch(`${BASE_URL}/routines/${id}`, {
        method: 'DELETE',
    });
    return handleResponse(res);
}
